# create file on remote then copy it here
- name: "Create file on remote (if absent) and copy it here"
  hosts: all
  become: True
  tasks: 
        - name: "Creating file if absent"
          ansible.builtin.file:
               path: "/tmp/newfile"
               state: touch
               mode: 0600
               modification_time: preserve
               access_time: preserve
        - name: "copying file from remote"
          ansible.builtin.fetch:
               src: "/tmp/newfile"
               flat: yes
               dest: "/tmp/newfile-{{ inventory_hostname }}"

