- name: Configuring wordpress to connect to the database
  hosts: localhost
  gather_facts: False
  become: true
  vars:
    wpconfig: 'wp-config.php'
  tasks:
    - name: get random secret keys
      uri:
        url: https://api.wordpress.org/secret-key/1.1/salt/
        return_content: yes
        body_format: json
      register: wordpress_keys
    - debug:
        var: wordpress_keys
    - name: delete existing bak file
      file:
        path: "/srv/www/wordpress/{{ wpconfig }}.bak"
        state: absent
    - name: run script to remove key placeholders
      script:
        chdir: /srv/www/wordpress/
        cmd: replacelines.py
        executable: /usr/bin/python3
        environment: /srv/www/wordpress/
    - name: update php config file with keys
      become_user: www-data
      blockinfile:
          #path: wp-config.php.bak
          path: "/srv/www/wordpress/{{ wpconfig }}.bak"
          marker: // {mark} ANSIBLE MANAGED BLOCK  
          block: 
            "{{ wordpress_keys.content }}"

   
