- name: "Install composer on Xubuntu slave"
  hosts: all
  become: True
  gather_facts: no
  vars:
    get_installer: 'curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php || /bin/true'
    get_signature: 'curl -sS https://composer.github.io/installer.sig'
  tasks:
        - name: "Update repository"
          apt: 
              update_cache: "yes"
        - name: "Installing requirements"
          apt:
            name:
                 - "curl"
                 - "php"
                 - "php-cli"
                 - "gnupg"
                 - "unzip"
                 - "nginx"
                 - "mysql-server"
                 - "php-fpm"
                 - "php-mysql"
            state: latest
        - name: "get composer installer"
          shell: 
            cmd: "{{ item }}"
          with_items:
            - "{{ get_installer }}"
          async: 20
          poll: 2
        - name: "Getting composer installer signature "
          shell:
                # "echo 'curl -sS https://composer.github.io/installer.sig'"
                # doesn't do the trick as it merely echoes the cmd string back
                # and that's not what we want
                "{{ get_signature }}"
          register: HASH # store the hash into a variable named HASH
        - name: "Verify installer "
          shell:
            cmd: >
              php -r 
              "if (hash_file('SHA384', '/tmp/composer-setup.php') === '$hashVal') 
              { echo 'Installer verified'; } 
              else { echo 'Installer corrupt'; unlink('composer-setup.php'); } 
              echo PHP_EOL;"
          register: status
          environment:
            hashVal: "{{ HASH.stdout }}" 

        - fail:
            msg: "Installer corrupt retry later"
          when: "status.stdout == 'Installer corrupt'"

        - debug: 
            msg: 
              - "hash is {{ HASH.stdout }}" # skipping the brace doesn't work
              - "status is {{ status.stdout }}"

        - name: "Installing composer"
          shell:
            cmd: >
              sudo php /tmp/composer-setup.php 
              --install-dir=/usr/local/bin 
              --filename=composer
          register: out
        - debug:
            msg: |
              "cmd output is: "
              "{{ out.stdout }}"
